version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - myapp_data:/rails/data
      - myapp-ruby-bundle-cache:/rails/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:
  myapp_data:
  ruby-bundle-cache: