# Make sure it matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.2

FROM ruby:$RUBY_VERSION

# Install dependencies
RUN apt-get update -qq && \
  apt-get install -y build-essential libvips nodejs postgresql-client libpq-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Set an environment variable to store the application's directory
# ENV APP_HOME /rails

# Create the application's directory and set it as the working directory
# RUN mkdir $APP_HOME
WORKDIR /rails

# Copy the Gemfile and Gemfile.lock into the working directory
COPY Gemfile Gemfile.lock ./

# Install the gems
RUN bundle install

# Copy the application code into the working directory
COPY . .

# Expose the default Rails server port
EXPOSE 3000

# Run the Rails server when the container starts
CMD ["rails", "server", "-b", "0.0.0.0"]